<?php

if (!defined('MANDALART_REGISTRATION_OPEN')) {
    define('MANDALART_REGISTRATION_OPEN', true);
}

if (!defined('MANDALART_REGISTER_RATE_MAX_PER_IP')) {
    define('MANDALART_REGISTER_RATE_MAX_PER_IP', 5);
}

if (!defined('MANDALART_REGISTER_RATE_WINDOW_SEC')) {
    define('MANDALART_REGISTER_RATE_WINDOW_SEC', 3600);
}

if (!defined('MANDALART_CONTACT_GUEST_RATE_MAX_PER_IP')) {
    define('MANDALART_CONTACT_GUEST_RATE_MAX_PER_IP', 12);
}

if (!defined('MANDALART_CONTACT_GUEST_RATE_WINDOW_SEC')) {
    define('MANDALART_CONTACT_GUEST_RATE_WINDOW_SEC', 3600);
}
