services:
  db:
    image: mysql:8.0
    container_name: mandalart-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mandalart
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - "./mandalart.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./backend
    container_name: mandalart-backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: mandalart
      JWT_SECRET: csereld_le_egy_min_32_karakteres_random_stringre
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - gallery_images_data:/var/www/html/backend/public/gallery_images

  web:
    build:
      context: .
    container_name: mandalart-web
    depends_on:
      - backend
    ports:
      - "8080:80"

  adminer:
      image: adminer
      restart: always
      ports:  
      - "8888:8080"

volumes:
  db_data:
  gallery_images_data:
